[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[redirects]]
  from = "http://tejamanikanta.com/*"
  to   = "https://tejamanikanta.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://www.tejamanikanta.com/*"
  to   = "https://tejamanikanta.com/:splat"
  status = 301
  force  = true
